### ISSUE TITLE
Atomiswave roms cause a "list index out of range error" in rom.py, line 264

### ISSUE THREAD

**Issue by notsonic** [DragonMinded/netboot#12]
The line in question:
https://github.com/DragonMinded/netboot/blob/4c39ce9493cc67e3dae5cc2ff0b99c75d67d778f/naomi/rom.py#L264

I apologize as I haven't really understood 100% what this is doing, but this line is causing an error with converted Atomiswave roms.
For example the indexes it's calculating for Demolish Fist look like:
```
[82, 67, 65, 68, 69, 77, 79, 68]
```
Where as a quick look at a normal Naomi game its all 1's or nothing.

**Comment by DragonMinded** [comment]
The sequences are supposed to be indexes into a different point in the ROM header for things like "insert coin to continue" or "add credits to continue", etc. They need to be in a particular range to point at the sequence texts themselves (https://github.com/DragonMinded/netboot/blob/4c39ce9493cc67e3dae5cc2ff0b99c75d67d778f/naomi/rom.py#L206). It looks like the AW conversions stuck some random data there, because the numbers should be between 0-7 inclusive.

I had a suspicion, so I pasted those values into python and:

```
>>> a = [82, 67, 65, 68, 69, 77, 79, 68]
>>> bytes(a)
b'RCADEMOD'
```

So it looks like some asshole has tagged the header in a spot they thought was "safe" to vandalize. Now, there's a few ways to handle this. First, take a hardline stance. Original ROMs (and well crafted ones) should follow the spec. `rom.py` should crash, because its referring to nonsense data that would never be found in a "real" ROM or even one created by libnaomi. But these already exist and unfortunately the people that make these ROMs love to tag them. So, the second is to make ROM.py assume there could be bad data (better practice anyway) and make sure to range check the sequence texts and choose the default (0) if they are out of range.

Either way, those ROM headers are borked, but ROM.py could handle it better.

**Comment by DragonMinded** [comment]
Okay, I patched rom.py to default to something sane when it hits these and it appears to work now. I also added in some patches for AW games so you don't have to keep two copies around if you are using these tools to boot.
